[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' https://res.cloudinary.com data:;
      media-src 'self' https://res.cloudinary.com https://*.supabase.co blob: data:;
      connect-src 'self' 
        https://res.cloudinary.com 
        https://aumwecuflxjndyrapnzx.supabase.co 
        https://xtpxmhyjcmiwxuuvtopj.supabase.co
        https://*.supabase.co
        https://*.supabase.in;
      frame-src 'none';
      object-src 'none';
      base-uri 'self';
      form-action 'self'
    """
    
[build.environment]
  NODE_VERSION = "18"

  [context.production.environment]
SUPABASE_URL= "https://xtpxmhyjcmiwxuuvtopj.supabase.co"
SUPABASE_ANON_KEY= "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0cHhtaHlqY21pd3h1dXZ0b3BqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NzQ1NjEsImV4cCI6MjA2MzM1MDU2MX0.agBNUNHeGkordVdHFy9IC3-XZlQSTtuow46efl_iarc"

    [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200